- name: add red.app to /etc/hosts
  lineinfile: dest=/etc/hosts line='127.0.0.1 red.app' owner=root group=root mode=0644
  sudo: yes

- name: add green.app to /etc/hosts
  lineinfile: dest=/etc/hosts line='127.0.0.1 green.app' owner=root group=root mode=0644
  sudo: yes

- name: add blue.app to /etc/hosts
  lineinfile: dest=/etc/hosts line='127.0.0.1 blue.app' owner=root group=root mode=0644
  sudo: yes
