- name: Download and install the Public Signing Key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: add elastic search repository
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' state=present

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install dependencies
  apt: name={{item}} state=present
  with_items:
    - openjdk-7-jre
    - elasticsearch

- name: laoding config
  copy: src={{ elasticsearch_conf }} dest="/{{ elasticsearch_conf }}"
  notify: restarting elasticsearch
