- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install couchdb
  apt: name={{item}} state=present
  with_items:
    - couchdb

- name: laoding config
  copy: src={{ couchdb_ini }} dest="/{{ couchdb_ini }}"
  notify: restarting couchdb
