swapfile_size: 256MB # for azavea.swapfile
app_key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA24/jS/94wfUHVfEvq1ZtIHntAy13Dc/7h/BTJcgpD6p5yTYaG2UXwvdp2KQMsqdS7Y6sFBx4sDNFzKySmOe7KrLKCO0hgX/HXSUzlIwfWtFsqNsepe6BanauFr6MPNmStp6yjQt+TiqtYpIP1PzHkMwOhE4qFaernjNJSNhXmFRzgdZ17soRWdPqzekJFKqXZ2uF48WfOeXoTzPhH4QhN/hl/b39LXj5iuZobHaergyq7vWq4WwbYxOyYRPQ1rVEcYMeO7rZxasX6/CQRuvUQk11Hvqrhck1Ekc+aaTSVrdN2CABS0Tnx+tzOJrdNsEvx2NoSOfAmejxQ+pV9FMf4w== grant.speelman@unboxedconsulting.com
ga_tracking_id: UA-64776587-2
db_server_ip: 41.79.78.65
app_domains:
  - upstream: za_ec
    ip: 41.79.78.69
    port: 9390
    domain: za-ec.public-grocery-price-book-api.co.za
    app_user: za_ec
    app_db_name: za_ec
    app_db_password: zaec123
  - upstream: za_fs
    ip: 41.79.78.69
    port: 9391
    domain: za-fs.public-grocery-price-book-api.co.za
    app_user: za_fs
    app_db_name: za_fs
    app_db_password: zafs123
  - upstream: za_gt
    ip: 41.79.78.69
    port: 9392
    domain: za-gt.public-grocery-price-book-api.co.za
    app_user: za_gt
    app_db_name: za_gt
    app_db_password: zagt123
  - upstream: za_nl
    ip: 41.79.78.69
    port: 9393
    domain: za-nl.public-grocery-price-book-api.co.za
    app_user: za_nl
    app_db_name: za_nl
    app_db_password: zanl123
  - upstream: za_lp
    ip: 41.79.78.69
    port: 9394
    domain: za-lp.public-grocery-price-book-api.co.za
    app_user: za_lp
    app_db_name: za_lp
    app_db_password: zalp123
  - upstream: za_mp
    ip: 41.79.78.69
    port: 9395
    domain: za-mp.public-grocery-price-book-api.co.za
    app_user: za_mp
    app_db_name: za_mp
    app_db_password: zamp123
  - upstream: za_nc
    ip: 41.79.78.69
    port: 9396
    domain: za-nc.public-grocery-price-book-api.co.za
    app_user: za_nc
    app_db_name: za_nc
    app_db_password: zanc123
  - upstream: za_nw
    ip: 41.79.78.69
    port: 9397
    domain: za-nw.public-grocery-price-book-api.co.za
    app_user: za_nw
    app_db_name: za_nw
    app_db_password: zanw123
  - upstream: za_wc
    ip: 41.79.78.69
    port: 9398
    domain: za-wc.public-grocery-price-book-api.co.za
    app_user: za_wc
    app_db_name: za_wc
    app_db_password: zawc123
