---
- name: Download and install the Ngnix Public Signing Key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: add ngnix repository
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: brightbox ruby repos
  apt_repository: repo='ppa:brightbox/ruby-ng' state=present

- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install software-properties-common
  apt: name=software-properties-common state=present

- name: installing ruby 2.2
  apt: name={{item}} state=present
  with_items:
    - ruby2.2
    - ruby2.2-dev
    - ruby-switch

- name: installing puma gem dependencies
  apt: name={{item}} state=present
  with_items:
    - libssl-dev

- name: installing capistrano gem dependencies
  apt: name={{item}} state=present
  with_items:
    - git

- name: Swith to ruby 2.2
  command: ruby-switch --set ruby2.2

- name: Install Bundler
  gem: name=bundler state=present

- name: install ngnix
  apt: name=nginx state=present

- name: remove default ngnix conf
  file: name=/etc/nginx/conf.d/default.conf state=absent

- name: upload ngnix price_book_api.conf
  template: src=etc/nginx/conf.d/price_book_api.conf.j2 dest=/etc/nginx/conf.d/price_book_api.conf mode=644 owner=root
  notify: restarting ngnix

- name: create price_book_api user
  user: name=price_book_api shell=/bin/bash createhome=yes

- name: create ssh directory
  file: path=~/.ssh state=directory
  sudo: yes
  sudo_user: price_book_api

- name: Set up authorized_keys for the price_book_api user
  authorized_key: user=price_book_api key="{{ item }}"
  with_file:
    - _keys/grant_petersen-speelman.pub


