- name: Download and install the Ngnix Public Signing Key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: add ngnix repository
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install ngnix
  apt: name=nginx state=present

- name: remove default ngnix conf
  file: name=/etc/nginx/conf.d/default.conf state=absent

- name: upload ngnix price_book_api.conf
  template: src=etc/nginx/conf.d/price_book_api.conf.j2 dest=/etc/nginx/conf.d/price_book_api.conf mode=644 owner=root
  notify: restarting ngnix
