---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install rbenv dependencies
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - git-core

- name: checkout rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=/usr/local/rbenv update=no

- name: setup rbenv profile.d
  copy: src=etc/profile.d/rbenv.sh dest=/etc/profile.d/rbenv.sh mode=755

- name: ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=/usr/local/rbenv/plugins/ruby-build

- name: Install jruby dependencies
  apt: name={{item}} state=present
  with_items:
    - openjdk-7-jre

- name: Install ruby dependencies
  apt: name={{item}} state=present
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: install ruby
  command: sudo -iu root rbenv install 2.2.0 creates=/usr/local/rbenv/versions/2.2.0

- name: set default ruby
  command: sudo -iu root rbenv global 2.2.0

- name: rbenv rehash
  command: sudo -iu root rbenv rehash

- name: Install Bundler
  gem: name=bundler state=present user_install=no executable=/usr/local/rbenv/shims/gem

- name: installing gem dependencies
  apt: name={{item}} state=present
  with_items:
    - sqlite3
    - libsqlite3-dev
    - libssl-dev
    - ruby-dev
    - g++

